{
 "title": "Sample Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Broker Messages Received",
   "type": "timeseries",
   "description": "$SYS/broker/messages/received",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "SELECT value FROM \"mqtt_stats\" WHERE $timeFilter AND statname = 'broker/messages/received'\n"
    }
   ]
  },
  {
   "title": "Broker Messages Sent",
   "type": "timeseries",
   "description": "$SYS/broker/messages/sent",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 0 },
   "targets": [
    {
     "query": "SELECT value FROM \"mqtt_stats\" WHERE $timeFilter AND statname = 'broker/messages/sent'\n"
    }
   ]
  },
  {
   "title": "Broker Subscriptions Count",
   "type": "timeseries",
   "description": "$SYS/broker/subscriptions/count",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "SELECT value FROM \"mqtt_stats\" WHERE $timeFilter AND statname = 'broker/subscriptions/count'\n"
    }
   ]
  },
  {
   "title": "Broker Clients Connected",
   "type": "timeseries",
   "description": "$SYS/broker/clients/connected",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 9 },
   "targets": [
    {
     "query": "SELECT value FROM \"mqtt_stats\" WHERE $timeFilter AND statname = 'broker/clients/connected'\n"
    }
   ]
  }
 ]
}